### ISSUE TITLE
+ selector in objects/forms.less

### ISSUE THREAD

**Issue by FlexCarver** [cbracco/cardinal#66]
Hello, I might be wrong - maybe it's because I work with grunt still - but the "+" selectors in objects/forms.less seem out of place to me?
line 9 .form-label + .form-input for example

line 1952 cardinal.css
.form-label + .form-input

is not a proper selector?
it doesn't work @ my end ...

I changed it to:
.form-label,
.form-input,
.form-select,
.form-textarea {
  .to-rem(margin-top, @form-label-margin);
}

to make it work?

**Comment by cbracco** [comment]
I'm not sure what your issue is. Please provide a more in-depth explanation and/or example of the problem you are experiencing. Thanks!

**Comment by FlexCarver** [comment]
First, after three days of hard work integrating your Framework, I was stunned to see the whole layout get smaller after changing the base font size. Suppose you are working on some sort of documentation, but I found the elegant way of increasing font sizes with the fz++ classes soon enough. Looking forward to more great surprises, great work, thanx, I use it for ComfortPages.com, u can have a look if interested.

The question I have is regarding line 1952 in cardinal.css:
.form-label + .form-input

This not a proper selector - with the plus sign there?
It doesn't work @ my end ...

I changed it to:
.form-label,
.form-input,
.form-select,
.form-textarea {
  .to-rem(margin-top, @form-label-margin);
}

to make it work?
I am probably not aware of some trick?

**Comment by cbracco** [comment]
The idea here is to only give a top margin to `.form-input` elements that have a `.form-label` element before it, to create a little space between the label and the input. If there is no `.form-label`, there is no need for the top margin.

**Comment by FlexCarver** [comment]
Thank you, I had never heard of the "+" selector. The reason it doesn't work in my forms is clear then -> I am using a grid-item for the label and input, meaning the label is not immediately before the input no more. I just have to add the margin to the input "p" grid-item, Thanx!

**Comment by FlexCarver** [comment]
Hi, thanx, I just updated my site with your new framework! 
(comfortpages.com)

Your modernizr script on your cardinall website is not loading, dead url !

Happy Weekend!
Ray

**Comment by cbracco** [comment]
No problem! I'm glad you were able to figure it out :smile: 

Also, nice catch on the Modernizr thing! Thanks for bringing that to my attention, will fix it up when I get a moment.
