### ISSUE TITLE
Embedded YouTube videos

### ISSUE THREAD

**Issue by badlydrawnrob** [cbracco/cardinal#72]
Nice to see basic styling for embedded content, but the `iframe` option isn't particularly useful for YouTube/Vimeo videos. You'd think they'd have figured a way to do this via their own embed method by now, but until they do I'd suggest adding a helper class:

    .youtube {
	  position: relative;
	  padding-bottom: 56.25%;
	  height: 0; overflow: hidden;
	  max-width: 100%;
    }
    .youtube iframe {
	  position: absolute;
	  top: 0; left: 0;
	  width: 100%; height: 100%;
    }

Only tested on a couple of browsers, but works well without the need for `js` — source: <http://embedresponsively.com>

**Comment by cbracco** [comment]
@badlydrawnrob familiar with that problem/solution, thanks! It's a bit outside the scope of Cardinal, I'd recommend adding it as a custom component to your project if it has that need.

**Comment by badlydrawnrob** [comment]
@cbracco Sure, thought I'd flag it up — it's a debatable one as far as default settings go. Seems you've thought of almost everything though with the current setup! Just trying to get my head around some of the utility helpers.
